"""Apply update_image_urls.sql (generated by fill_product_images.py) to the DB.

USAGE: backend\\.venv\\Scripts\\python.exe backend\\scripts\\apply_image_urls.py
"""

import asyncio
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from sqlalchemy import text
from app.core.database import AsyncSessionLocal, engine

SQL_PATH = Path(__file__).resolve().parent / "update_image_urls.sql"


async def apply() -> None:
    sqla_path = SQL_PATH
    if not sqla_path.exists():
        print(f"[error] {sqla_path} missing. Run fill_product_images.py first.")
        return
    statements = [
        stmt.strip()
        for stmt in sqla_path.read_text(encoding="utf-8").split(";")
        if stmt.strip() and stmt.strip().upper() not in {"BEGIN", "COMMIT"}
    ]
    async with AsyncSessionLocal() as session:
        for stmt in statements:
            await session.execute(text(stmt))
        await session.commit()
    await engine.dispose()
    print(f"Applied {len(statements)} statements from {SQL_PATH.name} — image_url column updated.")


if __name__ == "__main__":
    asyncio.run(apply())