BEGIN;
UPDATE products SET image_url = '/products/flour.jpg' WHERE name = 'Atta Flour 1kg';
UPDATE products SET image_url = '/products/chicken.jpg' WHERE name = 'Broiler Chicken 1kg';
UPDATE products SET image_url = '/products/egg.jpg' WHERE name = 'Farm Egg (1 piece)';
UPDATE products SET image_url = '/products/beef.jpg' WHERE name = 'Fresh Beef 1kg';
UPDATE products SET image_url = '/products/ginger.jpg' WHERE name = 'Fresh Ginger 250g';
UPDATE products SET image_url = '/products/milk.jpg' WHERE name = 'Fresh Milk 1 litre';
UPDATE products SET image_url = '/products/onion.jpg' WHERE name = 'Fresh Onion 1kg';
UPDATE products SET image_url = '/products/garlic.jpg' WHERE name = 'Garlic 500g';
UPDATE products SET image_url = '/products/green-chili.jpg' WHERE name = 'Green Chili 250g';
UPDATE products SET image_url = '/products/salt.jpg' WHERE name = 'Iodized Salt 1kg';
UPDATE products SET image_url = '/products/potato.jpg' WHERE name = 'Local Potato 1kg';
UPDATE products SET image_url = '/products/lentil.jpg' WHERE name = 'Masoor Dal 1kg';
UPDATE products SET image_url = '/products/rice.jpg' WHERE name = 'Miniket Rice 1kg';
UPDATE products SET image_url = '/products/biscuit.jpg' WHERE name = 'Mixed Biscuit Pack';
UPDATE products SET image_url = '/products/mutton.jpg' WHERE name = 'Mutton 1kg';
UPDATE products SET image_url = '/products/rice.jpg' WHERE name = 'Premium Basmati Rice 5kg';
UPDATE products SET image_url = '/products/tea.jpg' WHERE name = 'Premium Tea 500g';
UPDATE products SET image_url = '/products/tomato.jpg' WHERE name = 'Ripe Tomato 1kg';
UPDATE products SET image_url = '/products/cooking-oil.jpg' WHERE name = 'Soybean Oil 1 litre';
UPDATE products SET image_url = '/products/sugar.jpg' WHERE name = 'Sugar 1kg';
COMMIT;
